### ISSUE TITLE
create SWRLRuleEngine problem

### ISSUE THREAD

**Issue by tibagosi** [protegeproject/swrlapi#2]
I am trying to create a SWRLRuleEngine.
Following the wiki documentation of SWRLAPI Rule Engine, neither this:
 SWRLRuleEngine ruleEngine = SWRLAPIFactory.createSWRLRuleEngine(swrlapiOWLOntology);
nor this:
SWRLRuleEngine ruleEngine = SWRLAPIFactory.createSWRLRuleEngine("Drools", swrlapiOWLOntology);
is a valid method, since the method looks like:
public static SWRLRuleEngine createSWRLRuleEngine(SWRLAPIOWLOntology swrlapiOWLOntology,
			SWRLRuleEngineManager.TargetSWRLRuleEngineCreator swrlRuleEngineCreator)

So I was trying to create the following:
 TargetSWRLRuleEngineCreator recreator = DroolsFactory.getSWRLRuleEngineCreator();
SWRLRuleEngine ruleEngine = SWRLAPIFactory.createSWRLRuleEngine(swrlontology, recreator);

That gave me an 
org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.NoClassDefFoundError. Message: org/drools/runtime/rule/AgendaFilter
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:83)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:60)
	at org.swrlapi.core.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:236)

So I added org.drools, drools-api, 5.1.1 to my dependencies, and I get:
org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.IllegalArgumentException. Message: Unable to instantiate service for Class 'org.drools.KnowledgeBaseFactoryService'
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:83)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:60)
	at org.swrlapi.core.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:236)....

Am I missing some dependency or package?
Could you please help me?
Could you please update the documentation to reflect the code?
Thank you so much, looking forward to any reply.
Timi.

**Comment by vgezer** [comment]
@zippyrate Any updates on this? We are also experiencing the same problem.

@tibagosi Did you manage to solve the issue?

Thanks.

**Comment by martinjoconnor** [comment]
Note that the various SWRLAPI-related components have not yet been released, though, with the exception of the SWRLTab Protégé Plugin (see below), they should be usable. 

The above problem should be fixed. Note that the SWRLAPI currently depends on the 4.0.2-SNAPSHOT release of the OWLAPI (https://github.com/owlcs/owlapi) so you will need to download and compile that to successfully build this project because snapshots are not uploaded to Maven Central.

The current Protégé (5.0.0 Beta 17) is built using an earlier version of the OWLAPI so the plugin component will not work.

The various SWRLAPI-related components will be released as soon as Protégé is updated to the latest OWLAPI (which should happen in the next month).
