### ISSUE TITLE
Exception: built-in not yet implemented

### ISSUE THREAD

**Issue by mingzhenjun** [protegeproject/swrlapi#35]
Hello,

I tried to use the built-in swrlb:listIntersection (which is a defined built-in in the SWRLTab) in protege 5.2.0 and it threw an exception saying "built-in not yet implemented". It seems that the method swrlb:listIntersection has not been implemented in this version. Do I need to implement the method? If I use the SWRLBuiltInBridge component, are the steps the same as defining a new built-in methods?

Best regards,
Zhenjun Ming

**Comment by martinjoconnor** [comment]
List built-ins were not implemented because there are no canonical lists in OWL so it is not clear what they would operate on.

For querying purposes you could use SQWRL collections:

https://github.com/protegeproject/swrlapi/wiki/SQWRLCollections

Note that these collections are for querying purposes only. They cannot be used in SWRL rules to make inferences.
